### ISSUE TITLE
How to integrate ORMLite with Spring 4?

### ISSUE THREAD

**Issue by benedekh** [j256/ormlite-tests#1]
Dear @j256 !

ORMLite is great, I like it so much. I would like to ask, how to integrate the library with Spring 4 Framework? I tried the files uploaded to the [spring-example](https://github.com/j256/ormlite-tests/tree/master/src/test/java/com/j256/ormlite/examples/spring) folder, but it did not work at all.

I tried to use the annotations for the [Delivery](https://github.com/j256/ormlite-tests/blob/master/src/test/java/com/j256/ormlite/examples/spring/Delivery.java) class too, instead of the custom Java code DDL calls to build the table, but I received the following error trace executing the [Main](https://github.com/j256/ormlite-tests/blob/master/src/test/java/com/j256/ormlite/examples/spring/Main.java) class: http://pastebin.com/9z6Eu9N8

The other examples you provided worked fine, except for the [FieldConfig](https://github.com/j256/ormlite-jdbc/tree/master/src/test/java/com/j256/ormlite/examples/fieldConfig), which had some issues with the PostgreSQL database I use as a backend.

I send the whole project attached: [webdev.ormlite.examples.spring.zip](https://github.com/j256/ormlite-tests/files/309062/webdev.ormlite.examples.spring.zip)

May you have a look at it, and point out where I made mistakes? I really would like to use ORMLite with Spring instead of Hibernate.

Thank you so much for the help in advance.

Kind regards,
Ben

**Comment by benedekh** [comment]
Dear @j256!

Could you provide me some documentation about how to integrate ORMLite with Spring 4 MVC? I really would like to use ORMLite as DB access layer in order to avoid reimplementing the Dao classes...

Thank you for help in advance.

Kind regards,
Ben

**Comment by benedekh** [comment]
Never mind, solved the problem. If anyone wants to get familiar with Spring 4 MVC I recommed [this site's](http://websystique.com/) tutorials, which are quite good.

**Comment by j256** [comment]
Make sure you RTFM: http://ormlite.com/docs/spring

Also there is a spring example @benedekh https://github.com/j256/ormlite-tests/tree/master/src/test/java/com/j256/ormlite/examples/spring
